# Generated by Django 4.1.7 on 2023-03-18 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                ("image", models.CharField(max_length=200, verbose_name="Image url")),
                (
                    "likes",
                    models.PositiveIntegerField(default=0, verbose_name="likes count"),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="UUID",
                    ),
                ),
            ],
        ),
    ]
